name: Materials Discovery Lab

github_repo: https://github.com/thayer/materials
cloudcannon_dev_url: http://glamorous-beech.cloudvent.net
thayer_proxy_url: http://engineering.dartmouth.edu/materials-library

baseurl: "/materials-library"

update: http://glamorous-beech.cloudvent.net/update

grid_view_name_length: 22

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "materials"
    values:
      layout: "material"
  -
    scope:
      path: ""
      type: "processes"
    values:
      layout: "process"
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"

collections:
    materials:
        output: true
    processes:
        output: true
    products:
        output: true

material_classes:
    - Metals
    - Ceramics
    - Polymers
    - Hybrids

material_subclasses:
    - 'Metals: Ferrous'
    - 'Metals: Non-Ferrous'
    - 'Ceramics: Technical Ceramics'
    - 'Ceramics: Non-Technical Ceramics'
    - 'Ceramics: Glasses'
    - 'Polymers: Elastomers'
    - 'Polymers: Polymers' 
    - 'Hybrids: Composites'
    - 'Hybrids: Foams'
    - 'Hybrids: Natural Materials'

process_classes:
    - 'Shaping'
    - 'Joining'
    - 'Surface Treatment'

process_subclasses:
    - 'Joining: Adhesives'
    - 'Joining: Fasteners'
    - 'Joining: Mechanical Welding'
    - 'Joining: Thermal Welding'
    - 'Shaping: Additive Manufacturing'
    - 'Shaping: Casting'
    - 'Shaping: Composite Forming'
    - 'Shaping: Deformation'
    - 'Shaping: Machining'
    - 'Shaping: Molding'
    - 'Shaping: Powder Metods'
    - 'Surface Treatment: Heat Treatment'
    - 'Surface Treatment: Painting and Printing'
    - 'Surface Treatment: Polishing_Etching_Working_Texturing'
    - 'Surface Treatment: Surface Coating'

process_sub_subclasses:
    - 'Joining: Thermal Welding: Ceramics'
    - 'Joining: Thermal Welding: Metals'
    - 'Joining: Thermal Welding: Polymers'
    - 'Shaping: Additive Manufacturing: 3D Printing'
    - 'Shaping: Additive Manufacturing: Deposition Methods'
    - 'Shaping: Additive Manufacturing: Photopolymerization'
    - 'Shaping: Additive Manufacturing: Powder Bed Fusion'
    - 'Shaping: Additive Manufacturing: Sheet Lamination'
    - 'Shaping: Casting: Die Casting'
    - 'Shaping: Casting: Investment Casting'
    - 'Shaping: Casting: Sand Casting'
    - 'Shaping: Composite Forming: Advanced Composite Forming'
    - 'Shaping: Composite Forming: Conventional Composite Forming'
    - 'Shaping: Deformation: Bulk Deformation'
    - 'Shaping: Deformation: Sheet Deformation'
    - 'Shaping: Machining: Conventional Machining'
    - 'Shaping: Machining: Non-Conventional Machining'
    - 'Shaping: Molding: Thermoplastic Molding'
    - 'Shaping: Molding: Thermoset Molding'
    - 'Shaping: Powder Metods: Powder Molding'
    - 'Shaping: Powder Metods: Powder Pressing'




index_letters:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
