collections:
    materials:
        output: true
type:
            - Metals and Alloys
            - Ceramics and Glass
            - Hybrids
A-Z_index:
            - A
            - B
            - C
            - D
            - E
            - F
            - G
            - H
            - I
            - J
            - K
            - L
            - M
            - N
            - O
            - P
            - Q
            - R
            - S
            - T
            - U
            - V
            - W
            - X
            - Y
            - Z
