name: Materials Library
github_repo: https://github.com/thayer/matlib
github_pages_url: http://thayer.github.io/matlib
cloudcannon_dev_url: http://delightful-mushroom.cloudvent.net
baseurl: /matlib
name_length: 20

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "materials"
    values:
      layout: "material"

collections:
    materials:
        output: true

classes:
    - Metals
    - Ceramics
    - Polymers
    - Hybrids

subclasses:
    - 'Metals: Pure Metals'
    - 'Metals: Alloy Metals'
    - 'Hybrids: Composites'
    - 'Hybrids: Foams'
    - 'Hybrids: Naturals'

index_letters:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
