collections:
    materials:
        output: true
        
catagories:
    - Metals and Alloys
    - Ceramics and Glasses
    - Polymers and Elastomers
    - Hybrids

subcatagories:
    - None
    - Pure Metals
    - Metal Alloys
    - Composites
    - Foams
    - Naturals

index_letters:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z