name: Materials Discovery Lab

github_repo: https://github.com/thayer/materials
cloudcannon_dev_url: http://glamorous-beech.cloudvent.net
thayer_proxy_url: http://engineering.dartmouth.edu/materials-library

baseurl: "/materials-library"

update: http://glamorous-beech.cloudvent.net/update

grid_view_name_length: 22

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "materials"
    values:
      layout: "material"
  -
    scope:
      path: ""
      type: "processes"
    values:
      layout: "process"
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"

collections:
    materials:
        output: true
    processes:
        output: true
    products:
        output: true

classes:
    - Metals
    - Ceramics
    - Polymers
    - Hybrids

subclasses:
    - 'Metals: Pure Metals'
    - 'Metals: Alloy Metals'
    - 'Ceramics: Technical Ceramics'
    - 'Ceramics: Glasses'
    - 'Ceramics: Cement and Concrete'
    - 'Ceramics: Fired Clays'
    - 'Ceramics: Minerals and Stone'
    - 'Polymers: Elastomers'
    - 'Polymers: Thermoplastics'
    - 'Polymers: Thermosets'
    - 'Hybrids: Composites'
    - 'Hybrids: Foams'
    - 'Hybrids: Naturals'

index_letters:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
