collections:
    materials:
        output: true
types:
    - Metals and Alloys
        categories: ['Pure Metals', 'Metal Alloys']
    - Ceramics and Glass
        categories: ['one', 'two']
    - Hybrids

index_letters:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z